name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'chromium/**'

env:
  CONTEXT_PATH: "./chromium"

jobs:
  chromium:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set env vars
      run: echo "CHROMIUM_VERSION=$(grep 'ARG CHROMIUM_VERSION' ${{ env.CONTEXT_PATH }}/Dockerfile | cut -d '=' -f2 )" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.CONTEXT_PATH }}/
        file: ${{ env.CONTEXT_PATH }}/Dockerfile
        push: true
        tags: joinsolutions/chromium:${{ env.CHROMIUM_VERSION }}
