name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'cimg-node-browsers/**'

env:
  CONTEXT_PATH: "./cimg-node-browsers"

jobs:
  cimg-node-browsers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set env vars
      run: echo "IMG_VERSION=$(grep 'ARG CIMG_NODE_VERSION' ${{ env.CONTEXT_PATH }}/Dockerfile | cut -d '=' -f2 )" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.CONTEXT_PATH }}/
        file: ${{ env.CONTEXT_PATH }}/Dockerfile
        push: true
        tags: joinsolutions/cimg-node:${{ env.IMG_VERSION }}-browsers
