name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'nexus/**'
      - '.github/workflows/nexus.yml'

env:
  CONTEXT_PATH: './nexus'

jobs:
  nexus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ env.CONTEXT_PATH }}/
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          tags: joinsolutions/nexus:3.49.0
