name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'verdaccio/**'
      - '.github/workflows/verdaccio.yml'

env:
  CONTEXT_PATH: './verdaccio'

jobs:
  verdaccio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTEXT_PATH }}/
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          push: true
          tags: joinsolutions/verdaccio:5.21.1
